$(function(){
			$(".ul1").animate({top:"0"},700)
			$(".logo").animate({top:"0"},700)
			$(".kehu").click(function(){
				window.open("kehu.html");
			});
			$(".tiyan").mouseenter(function(){
				$(this).animate({backgroundColor:"#BF3826"},100);
			});
			$(".tiyan").mouseleave(function(){
				$(this).animate({backgroundColor:"#F39800"},100);
			});
			$(".item-box-box").mouseenter(function(){
				$(this).css("background-color","#F5F5F5")
				$(".item-box-span").eq($(this).index()).stop().animate({width:"30px"},500);
			});
			$(".item-box-box").mouseleave(function(){
				$(this).css("background-color","")
				$(".item-box-span").stop().animate({width:"20px"},500);
			});
			$(".zjyjl-item-box").mouseenter(function(){
				$(this).children("img").eq($(this).index()).css({"transition":"1s","-webkit-transform":"rotate(360deg)"})
				$(this).children("h3").eq($(this).index()).css("color","#F59839");
			});
			$(".zjyjl-item-box").mouseleave(function(){
				$(this).children("img").eq($(this).index()).css({"transition":"1s","-webkit-transform":"rotate(0deg)"})
				$(this).children("h3").eq($(this).index()).css("color","");
			});
			$(".zjyjl-item-tiyan").mouseenter(function(){
				$(this).stop().animate({backgroundColor:"#F39800"},500);
				$(this).css("color","white");
			});
			$(".zjyjl-item-tiyan").mouseleave(function(){
				$(this).stop().animate({backgroundColor:""},500);
				$(this).css("color","#F39800");
			});
			$(".PC,.Android").mouseenter(function(){
				$(this).stop().animate({backgroundColor:"#fff"},500);
			});
			$(".PC,.Android").mouseleave(function(){
				$(this).stop().animate({backgroundColor:"rgba(0,0,0,0)"},500);
			});
			$(".bottom-tiyan").mouseenter(function(){
				$(this).css("color","#000");
				$(this).stop().animate({backgroundColor:"#fff"},200);
			});
			$(".bottom-tiyan").mouseleave(function(){
				$(this).css("color","");
				$(this).stop().animate({backgroundColor:"rgba(0,0,0,0)"},200);
			});
			$(window).bind("scroll", function(){
    		var top = $(this).scrollTop(); // 当前窗口的滚动距离
    		console.log(top);
    		if(top>1000){
    			$(".Android").css("margin-left","200px");
    		}
			});
    	});